name             'firewalld'
maintainer       'Stephen Sadowski'
maintainer_email 'stephen.sadowski@sjsadowski.com'
source_url       'https://github.com/sjsadowski/firewalld-cookbook'
issues_url       'https://github.com/sjsadowski/firewalld-cookbook/issues'
chef_version     '>= 13.0'
license          'Apache-2.0'
description      'Installs/Configures firewalld'
version          '1.2.2'

supports         'fedora', '>= 15.0'
supports         'centos', '>= 7.0'
supports         'redhat', '>= 7.0'
supports         'ubuntu', '>= 14.04'
supports         'debian', '>= 8.0'
